package cloudy

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

var fakeJwt = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJ1cG4iOiJUZXN0LlVzZXJAdXBuLmNvbSIsIklzc3VlciI6Iklzc3VlciIsInByZWZlcnJlZF91c2VybmFtZSI6IlVzZXJOYW1lIiwiZXhwIjoxNjU0MDE0MDIxLCJpYXQiOjE2NTQwMTQwMjEsImVtYWlsIjoiVGVzdC5Vc2VyQGVtYWlsLmNvbSJ9.zUKGWpoo6xM4gzniTUwsV3wSK-z7xBVNoKvEWNgoupw"
var fakeJwt2 = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4NXgwU1dKWHhIOTJNR3JRdGlfZ0ViSlFFZnQ3bGJaMkNNR01odXZPU1A4In0.eyJleHAiOjE3MjYxNTgwMDgsImlhdCI6MTcyNjE1Nzk0OCwiYXV0aF90aW1lIjoxNzI2MTU3ODA5LCJqdGkiOiJmMjNhOTlkNC1hNjgyLTQxODctYTk3ZC03NmI5NDE5NzYzYWEiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLXZ1bGNhbi5hcmtsb3VkLnVzL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsibWFzdGVyLXJlYWxtIiwiYWNjb3VudCJdLCJzdWIiOiI0NTBhZWNiNS0zZTIxLTQ5MWMtYTA3Ni00NTdjZjExMTNkOTUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwb3J0YWwtZGV2Iiwic2Vzc2lvbl9zdGF0ZSI6ImU5M2Y0NmM4LTAxMTctNDFkNC1iOWE5LWMxM2MwMzU2OTQ5YyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9wb3J0YWxkZXYtcHZmLmFya2xvdWQudXMiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImNyZWF0ZS1yZWFsbSIsImRlZmF1bHQtcm9sZXMtbWFzdGVyIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIiwic2lkIjoiZTkzZjQ2YzgtMDExNy00MWQ0LWI5YTktYzEzYzAzNTY5NDljIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiU3RldmUgTWNGaWUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzbWNmaWUiLCJnaXZlbl9uYW1lIjoiU3RldmUiLCJmYW1pbHlfbmFtZSI6Ik1jRmllIiwiZW1haWwiOiJzbWNmaWVAaW50LnZ1bGNhbmZvcmdlZGV2LnVzIn0.XTqFL-k7EoH-fryUCMR0B6b2yxp5QvckFmXIalwRdZrH-1UvKf7wPH6RsNRMSb3RbF5k9XcR-f4vItlEqvg30WZHBjXgZikATKMHanvBG-hOQPuVI_RS3KLwuPFwzqrSeP6A9b5ttGlZfR7f5n1f8nJKVd3nEVaxCe3-2QqUW3jLd7aoklVBq5_VEiImGPi8zt1LuY2gPRUSmb7nODUmdDR36-ek7WZ4Y2-RlXfNwRHtZ3bhglKrzUP0y21Gjr0gPsodeqof90gj4kxUlL0k9FfeK49eJFfur38Q_MsY7H4DI2V1hqcRWNtpqTgvfG7zt4U8xJeGcBvNg9o_nBnVrg"

func TestJWT(t *testing.T) {
	jwt, err := ParseToken(fakeJwt)

	assert.Nil(t, err)
	assert.True(t, jwt.IsAuthenticated())
	// assert.Equal(t, jwt.Email, "test.user@email.com")
	// assert.Equal(t, jwt.UPN, "test.user@upn.com")
}

func TestJWT2(t *testing.T) {
	jwt, err := ParseToken(fakeJwt2)

	assert.Nil(t, err)
	assert.True(t, jwt.IsAuthenticated())
	assert.NotEmpty(t, jwt.Email)

}
