---
swagger: "2.0"
info:
  description: "Cloudy Model"
  version: "1.0.0"
  title: Cloudy Model API"
basePath: "/cloudy"
tags: 
- name: User 
schemes:
- "https"
paths:
  /nothing:
    options:
      operationId: "nothing"
      produces:
      - "application/json"
      tags:
      - User
      responses:
        200:
          description: "200 response"
definitions:
  User:
    type: object
    properties: 
      ID:
        type: string
      FirstName:
        type: string
      LastName:
        type: string
      JobTitle:
        type: string
      DisplayName:
        type: string
      Email:
        type: string
      Company: 
        type: string
      Department:
        type: string
      Citizenship:
        type: string
      ContractNumber:
        type: string
      ContractDate:
        type: string
      ProgramRole:
        type: string
      AccountType:
        type: string
      UPN:
        type: string
      MobilePhone:
        type: string
      OfficePhone:
        type: string
      Password:
        type: string
      MustChangePassword:
        type: boolean
      GitLabOnboardingIssue:
        type: number
        format: integer
      LastSignInDate:
        type: string
        format: datetime
      Enabled: 
        type: boolean
      ActionLog:
        type: string
  ErrorMessage: 
    type: object
    properties: 
      ID: 
        type: string
      Msg: 
        type: string
      Details: 
        type: string
  Group:
    type: object
    properties: 
      ID: 
        type: string
      Name: 
        type: string
      Type: 
        type: string
      Source: 
        type: string
      Extra:
        type: object
  Invite:
    type: object
    properties:
      User:
        $ref: '#/definitions/User'
      RedirectUrl:
        type: string
      SendEmail:
        type: boolean
      Extra:
        type: object
  AzureVirtualDesktop:
    type: object
    properties: 
      ResourceGroup:
        type: string
      UserPrincipalName:
        type: string
      UserObjectId:
        type: string
      HostPoolName:
        type: string
      SessionHost:
        type: string
      RoleId:
        type: string
      Extra:
        type: object
  Mailer:
    type: object
    properties: 
      HelpDeskEmail:
        type: string
      InviteEmailRedirect:
        type: string
      KnowlegeBaseUrl:
        type: string
      LoginUrl:
        type: string
      ProgramName:
        type: string
      Host:
        type: string
      Port:
        type: string
      Username:
        type: string
      Password:
        type: string
      