---
swagger: "2.0"
info:
  description: "Cloudy Model"
  version: "1.0.0"
  title: Cloudy Model API"
basePath: "/cloudy"
tags: 
- name: User 
schemes:
- "https"
paths:
  /nothing:
    options:
      operationId: "nothing"
      produces:
      - "application/json"
      tags:
      - User
      responses:
        200:
          description: "200 response"
definitions:
  User:
    type: object
    properties:
      uid:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      displayName:
        type: string
      username:
        type: string
      enabled:
        type: boolean
      attributes:
        type: object
        additionalProperties:
          type: string
  ErrorMessage: 
    type: object
    properties: 
      ID: 
        type: string
      Msg: 
        type: string
      Details: 
        type: string
  Group:
    type: object
    properties: 
      ID: 
        type: string
      Name: 
        type: string
      Type: 
        type: string
      Source: 
        type: string
      Extra:
        type: object
  Invite:
    type: object
    properties:
      User:
        $ref: '#/definitions/User'
      RedirectUrl:
        type: string
      SendEmail:
        type: boolean
      Extra:
        type: object
  AzureVirtualDesktop:
    type: object
    properties: 
      ResourceGroup:
        type: string
      UserPrincipalName:
        type: string
      UserObjectId:
        type: string
      HostPoolName:
        type: string
      SessionHost:
        type: string
      RoleId:
        type: string
      Extra:
        type: object
  Email:
    type: object
    properties:
      Host:
        type: string
      Port:
        type: string
      From:
        type: string
      Password:
        type: string
      AuthenticationRequired:
        type: boolean
