// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AvdPersonalStack Represents a single AVD stack, with exactly one host pool, one workspace, one app group, one remote desktop app, and any session hosts.
//
// swagger:model AvdPersonalStack
type AvdPersonalStack struct {

	// The application group ID in the stack
	AppGroupID string `json:"appGroupId,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expiresAt,omitempty"`

	// The host pool ID in the stack
	HostPoolID string `json:"hostPoolId,omitempty"`

	// Unique identifier for the stack (resource group or generated ID)
	ID string `json:"id,omitempty"`

	// last sync
	// Format: date-time
	LastSync strfmt.DateTime `json:"lastSync,omitempty"`

	// Azure location
	Location string `json:"location,omitempty"`

	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`

	// Resource group for the stack
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// List of session host IDs in the host pool
	SessionHostIds []string `json:"sessionHostIds"`

	// Stack status (e.g., Active, Deleting)
	Status string `json:"status,omitempty"`

	// Suffix used for resource grouping
	Suffix string `json:"suffix,omitempty"`

	// The workspace ID in the stack
	WorkspaceID string `json:"workspaceId,omitempty"`
}

// Validate validates this avd personal stack
func (m *AvdPersonalStack) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSync(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AvdPersonalStack) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expiresAt", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AvdPersonalStack) validateLastSync(formats strfmt.Registry) error {
	if swag.IsZero(m.LastSync) { // not required
		return nil
	}

	if err := validate.FormatOf("lastSync", "body", "date-time", m.LastSync.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this avd personal stack based on context it is used
func (m *AvdPersonalStack) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AvdPersonalStack) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AvdPersonalStack) UnmarshalBinary(b []byte) error {
	var res AvdPersonalStack
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
