// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AvdAppGroup avd app group
//
// swagger:model AvdAppGroup
type AvdAppGroup struct {

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expiresAt,omitempty"`

	// Linked host pool ID
	HostPoolID string `json:"hostPoolId,omitempty"`

	// App group name or resource ID
	ID string `json:"id,omitempty"`

	// last sync
	// Format: date-time
	LastSync strfmt.DateTime `json:"lastSync,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`

	// resource group
	ResourceGroup string `json:"resourceGroup,omitempty"`

	// List of linked session hosts
	SessionHosts []*AvdSessionHost `json:"sessionHosts"`

	// status
	Status string `json:"status,omitempty"`

	// Linked workspace ID
	WorkspaceID string `json:"workspaceId,omitempty"`
}

// Validate validates this avd app group
func (m *AvdAppGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSync(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionHosts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AvdAppGroup) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expiresAt", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AvdAppGroup) validateLastSync(formats strfmt.Registry) error {
	if swag.IsZero(m.LastSync) { // not required
		return nil
	}

	if err := validate.FormatOf("lastSync", "body", "date-time", m.LastSync.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AvdAppGroup) validateSessionHosts(formats strfmt.Registry) error {
	if swag.IsZero(m.SessionHosts) { // not required
		return nil
	}

	for i := 0; i < len(m.SessionHosts); i++ {
		if swag.IsZero(m.SessionHosts[i]) { // not required
			continue
		}

		if m.SessionHosts[i] != nil {
			if err := m.SessionHosts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sessionHosts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sessionHosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this avd app group based on the context it is used
func (m *AvdAppGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSessionHosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AvdAppGroup) contextValidateSessionHosts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SessionHosts); i++ {

		if m.SessionHosts[i] != nil {
			if err := m.SessionHosts[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sessionHosts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("sessionHosts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AvdAppGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AvdAppGroup) UnmarshalBinary(b []byte) error {
	var res AvdAppGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
