// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AzureVirtualDesktop azure virtual desktop
//
// swagger:model AzureVirtualDesktop
type AzureVirtualDesktop struct {

	// extra
	Extra interface{} `json:"Extra,omitempty"`

	// host pool name
	HostPoolName string `json:"HostPoolName,omitempty"`

	// resource group
	ResourceGroup string `json:"ResourceGroup,omitempty"`

	// role Id
	RoleID string `json:"RoleId,omitempty"`

	// session host
	SessionHost string `json:"SessionHost,omitempty"`

	// user object Id
	UserObjectID string `json:"UserObjectId,omitempty"`

	// user principal name
	UserPrincipalName string `json:"UserPrincipalName,omitempty"`
}

// Validate validates this azure virtual desktop
func (m *AzureVirtualDesktop) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this azure virtual desktop based on context it is used
func (m *AzureVirtualDesktop) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureVirtualDesktop) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureVirtualDesktop) UnmarshalBinary(b []byte) error {
	var res AzureVirtualDesktop
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
