// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Mailer mailer
//
// swagger:model Mailer
type Mailer struct {

	// help desk email
	HelpDeskEmail string `json:"HelpDeskEmail,omitempty"`

	// invite email redirect
	InviteEmailRedirect string `json:"InviteEmailRedirect,omitempty"`

	// knowlege base Url
	KnowlegeBaseURL string `json:"KnowlegeBaseUrl,omitempty"`

	// login Url
	LoginURL string `json:"LoginUrl,omitempty"`

	// program name
	ProgramName string `json:"ProgramName,omitempty"`
}

// Validate validates this mailer
func (m *Mailer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mailer based on context it is used
func (m *Mailer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Mailer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Mailer) UnmarshalBinary(b []byte) error {
	var res Mailer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
