// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecurityProfileConfiguration security profile configuration
//
// swagger:model SecurityProfileConfiguration
type SecurityProfileConfiguration struct {

	// flag for the trusted launch setting when creating a virtual machine
	SecurityTypes SecurityTypes `json:"securityTypes,omitempty"`
}

// Validate validates this security profile configuration
func (m *SecurityProfileConfiguration) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecurityTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SecurityProfileConfiguration) validateSecurityTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.SecurityTypes) { // not required
		return nil
	}

	if err := m.SecurityTypes.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("securityTypes")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("securityTypes")
		}
		return err
	}

	return nil
}

// ContextValidate validate this security profile configuration based on the context it is used
func (m *SecurityProfileConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSecurityTypes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SecurityProfileConfiguration) contextValidateSecurityTypes(ctx context.Context, formats strfmt.Registry) error {

	if err := m.SecurityTypes.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("securityTypes")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("securityTypes")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SecurityProfileConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecurityProfileConfiguration) UnmarshalBinary(b []byte) error {
	var res SecurityProfileConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
