// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// User user
//
// swagger:model User
type User struct {

	// company
	Company string `json:"Company,omitempty"`

	// custom security attributes
	CustomSecurityAttributes string `json:"CustomSecurityAttributes,omitempty"`

	// department
	Department string `json:"Department,omitempty"`

	// display name
	DisplayName string `json:"DisplayName,omitempty"`

	// email
	Email string `json:"Email,omitempty"`

	// extra
	Extra interface{} `json:"Extra,omitempty"`

	// first name
	FirstName string `json:"FirstName,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`

	// job title
	JobTitle string `json:"JobTitle,omitempty"`

	// last name
	LastName string `json:"LastName,omitempty"`

	// mobile phone
	MobilePhone string `json:"MobilePhone,omitempty"`

	// must change password
	MustChangePassword bool `json:"MustChangePassword,omitempty"`

	// office phone
	OfficePhone string `json:"OfficePhone,omitempty"`

	// password
	Password string `json:"Password,omitempty"`

	// source
	Source string `json:"Source,omitempty"`

	// status
	Status string `json:"Status,omitempty"`

	// user name
	UserName string `json:"UserName,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user based on context it is used
func (m *User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
