// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualMachineConnection Information required to establish a connection to a virtual machine.
//
// swagger:model VirtualMachineConnection
type VirtualMachineConnection struct {

	// The remote desktop provider
	RemoteDesktopProvider string `json:"remoteDesktopProvider,omitempty"`

	// URL to establish the remote desktop connection.
	URL string `json:"url,omitempty"`

	// Unique identifier of the virtual machine.
	VMID string `json:"vmId,omitempty"`
}

// Validate validates this virtual machine connection
func (m *VirtualMachineConnection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this virtual machine connection based on context it is used
func (m *VirtualMachineConnection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualMachineConnection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualMachineConnection) UnmarshalBinary(b []byte) error {
	var res VirtualMachineConnection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
